version: "3"

services:
  android:
    container_name: simple_app_blocker
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /simple_app_blocker
    command: ./gradlew setup bundleDebug
    volumes:
      - .:/simple_app_blocker
