---
name: Feature Request
description: 機能を追加したい
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: 追加したいもの
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: なぜ必要か
    validations:
      required: true
